# version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    container_name: job-tracker-backend
    build:
      context: ./backend/job-tracker-backend
      dockerfile: Dockerfile
    command: sh -lc "uv run alembic upgrade head && uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend/job-tracker-backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    container_name: job-tracker-frontend
    build:
      context: ./frontend/job-tracker-frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/job-tracker-frontend:/job-tracker-frontend
      - /job-tracker-frontend/node_modules
    ports:
      - "5000:5000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - HOST=0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: