"""_remove_unwanted_table

Revision ID: d4ae3cb93b77
Revises: 20260929_batches_and_verdicts
Create Date: 2026-09-30 09:55:50.058970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4ae3cb93b77'
down_revision: Union[str, Sequence[str], None] = '20260929_batches_and_verdicts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('feedback')
    op.drop_table('deadlines')
    op.drop_table('peerreviews')            # child of journalsubmissions
    op.drop_table('journalsubmissions')     # after peerreviews
    op.drop_table('conferencepresentations')  # child of conferences
    op.drop_table('conferences')            # after its child
    op.drop_index(op.f('submissionhistory_entity_created_idx'), table_name='submissionhistory')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('submissionhistory_entity_created_idx'), 'submissionhistory', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('journalsubmissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('journalsubmissions_paper_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('journalsubmissions_pkey'))
    )
    op.create_table('conferencepresentations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conference_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('presenter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], name=op.f('conferencepresentations_conference_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('conferencepresentations_paper_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presenter_id'], ['users.id'], name=op.f('conferencepresentations_presenter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conferencepresentations_pkey'))
    )
    op.create_table('conferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conference_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('conferences_pkey'))
    )
    op.create_table('peerreviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('journal_submission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal_submission_id'], ['journalsubmissions.id'], name=op.f('peerreviews_journal_submission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('peerreviews_reviewer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('peerreviews_pkey'))
    )
    op.create_table('deadlines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deadline_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('deadlines_created_by_fkey')),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('deadlines_paper_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('deadlines_pkey'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('progress_report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['progress_report_id'], ['progressreports.id'], name=op.f('feedback_progress_report_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], name=op.f('feedback_supervisor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    # ### end Alembic commands ###
