"""convert users.role to native enum

Revision ID: d7e69749a726
Revises: 20260914_departments_is_active
Create Date: 2026-09-14 11:58:25.017267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e69749a726'
down_revision: Union[str, Sequence[str], None] = '20260914_departments_is_active'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('supervisor_id', sa.Uuid(), nullable=False))
    op.add_column('papers', sa.Column('proposal_id', sa.Uuid(), nullable=True))
    op.add_column('papers', sa.Column('cluster_id', sa.Uuid(), nullable=False))
    op.add_column('papers', sa.Column('title', sa.String(), nullable=False))
    op.add_column('papers', sa.Column('status', sa.String(), nullable=False))
    op.add_column('papers', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'papers', 'clusters', ['cluster_id'], ['id'])
    op.create_foreign_key(None, 'papers', 'users', ['supervisor_id'], ['id'])
    op.create_foreign_key(None, 'papers', 'proposals', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'proposalcandidates', 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.Enum('super_admin', 'admin', 'student', 'professor', 'external', name='role'),
    #            existing_nullable=False)
    
    op.alter_column(
    'users',
    'role',
    existing_type=sa.VARCHAR(),
    type_=sa.Enum(
        'super_admin',
        'admin',
        'student',
        'professor',
        'external',
        name='role'
    ),
    existing_nullable=False,
    postgresql_using='role::role'
)
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'admin', 'student', 'professor', 'external', name='role'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'proposalcandidates', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'papers', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'papers', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_column('papers', 'created_at')
    op.drop_column('papers', 'status')
    op.drop_column('papers', 'title')
    op.drop_column('papers', 'cluster_id')
    op.drop_column('papers', 'proposal_id')
    op.drop_column('papers', 'supervisor_id')
    # ### end Alembic commands ###
