[project]
name = "job-tracker-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "alembic>=1.13.0",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "graphene>=3.4.3",
    "graphene-sqlalchemy>=2.1.0",
    "black>=26.5.1",
    "python-dotenv>=1.2.2",
    "strawberry-graphql[fastapi]>=0.324.0",
    "libcst>=1.9.0",
    "pwdlib[argon2]>=0.3.1",
    "python-jose[cryptography]>=3.5.0",
    "uvicorn>=0.52.1",
    "pyjwt==2.13.0",
]
